create database country;
show databases;
use countrY;
select database();
select user();
drop database country;
create table State(ID int,Name varchar(10),capital varchar(10));
create table city(id int,name varchar(10),state_name varchar(10));
insert into state values(12,'Karnataka','Bengaluru');
insert into state values(11,'Maha','Mumbai');
insert into state(id) values(11);
insert into state(name) values('Goa');
select * from state;
insert into city values(45,'VIJAYAPURA','karnataka');
insert into city values(30,'pune','Maha');
select * from city;